services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-init db.d/mongo-init.js:ro
    networks:
      - video_network
  springboot-app:
    image: video-stream:latest
    container_name: springboot-app
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongo:27017/video-ts?authSource=admin
    ports:
      - '8089:8089'
    depends_on:
      - mongo
    networks:
      - video_network
    volumes:
      - /home/ubuntu:/home/ubuntu
    command: >
        /bin/sh -c "mkdir -p /home/ubuntu && chmod 777 /home/ubuntu"
networks:
  video_network:
    driver: bridge
volumes:
  mongo_data: